# Generated by Django 5.1.6 on 2026-01-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_response', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlresponse',
            name='id',
        ),
        migrations.AddField(
            model_name='mlresponse',
            name='response_record_id',
            field=models.CharField(db_index=True, default=0, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mlresponse',
            name='event_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
