# Generated by Django 5.1.6 on 2026-01-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_response', '0002_remove_mlresponse_id_mlresponse_response_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlresponse',
            name='response_record_id',
            field=models.CharField(db_index=True, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
