# Generated by Django 5.1.6 on 2026-01-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_response', '0003_alter_mlresponse_response_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlresponse',
            name='confidence',
        ),
    ]
