# Generated by Django 5.1.6 on 2026-01-17 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_id', models.UUIDField(db_index=True)),
                ('owner_user_id', models.UUIDField(db_index=True)),
                ('asset_type', models.CharField(choices=[('soil_sensor', 'Soil Sensor'), ('irrigation_controller', 'Irrigation Controller'), ('gateway', 'Farm Gateway'), ('weather_station', 'Weather Station')], max_length=50)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_os', models.CharField(blank=True, max_length=50, null=True)),
                ('baseline_lat', models.FloatField()),
                ('baseline_long', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
