# Generated by Django 5.1.6 on 2026-01-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='farm_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner_user_id',
            field=models.CharField(max_length=20),
        ),
    ]
