# Generated by Django 5.1.6 on 2026-01-17 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_user_id', models.UUIDField(db_index=True)),
                ('farm_name', models.CharField(max_length=150)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('area_in_acres', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
