# Generated by Django 5.1.6 on 2026-01-17 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('asset_id', models.UUIDField(db_index=True)),
                ('asset_type', models.CharField(choices=[('soil_sensor', 'Soil Sensor'), ('irrigation_controller', 'Irrigation Controller'), ('gateway', 'Gateway'), ('weather_station', 'Weather Station')], max_length=50)),
                ('device_id', models.UUIDField(db_index=True)),
                ('device_type', models.CharField(max_length=50)),
                ('device_os', models.CharField(max_length=50)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_role', models.CharField(blank=True, max_length=30, null=True)),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('read', 'Read'), ('write', 'Write'), ('update', 'Update'), ('delete', 'Delete'), ('config_change', 'Config Change')], max_length=30)),
                ('resource_type', models.CharField(max_length=50)),
                ('auth_status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=20)),
                ('failed_auth_attempts_5min', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField()),
                ('geo_lat', models.FloatField()),
                ('geo_long', models.FloatField()),
                ('geo_distance_from_baseline_km', models.FloatField()),
                ('farm_lat', models.FloatField()),
                ('farm_long', models.FloatField()),
                ('soil_moisture_percent', models.FloatField(blank=True, null=True)),
                ('soil_temperature', models.FloatField(blank=True, null=True)),
                ('soil_humidity', models.FloatField(blank=True, null=True)),
                ('irrigation_water_volume_ltrs', models.FloatField(blank=True, null=True)),
                ('water_consistency_score', models.FloatField(blank=True, null=True)),
                ('sensor_reading_variance', models.FloatField(blank=True, null=True)),
                ('sensor_signal_strength', models.FloatField(blank=True, null=True)),
                ('config_change_flag', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('anomaly_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
