# Generated by Django 5.1.6 on 2026-01-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_payload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityevent',
            name='anomaly_reason',
        ),
        migrations.RemoveField(
            model_name='securityevent',
            name='anomaly_score',
        ),
        migrations.RemoveField(
            model_name='securityevent',
            name='user_id',
        ),
        migrations.AddField(
            model_name='securityevent',
            name='farm_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='owner_user_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='asset_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='device_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
