# Generated by Django 5.1.6 on 2026-01-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_payload', '0002_remove_securityevent_anomaly_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('read', 'Read'), ('transmit', 'Transmit'), ('update', 'Update'), ('config_change', 'Config Change')], max_length=30),
        ),
    ]
