# Generated by Django 5.1.6 on 2026-01-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_payload', '0004_remove_securityevent_asset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='farm_id',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='farm_lat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='farm_long',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='geo_distance_from_baseline_km',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='irrigation_water_volume_ltrs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='sensor_reading_variance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='sensor_signal_strength',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='soil_humidity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='soil_moisture_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='soil_temperature',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='water_consistency_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
